### ISSUE TITLE
Error related to image

### ISSUE THREAD

**Issue by kalkiboru111** [DoubleDice-com/beta#1]
I uploaded a weird image format (.mpc). It presented me with an error only a few pages later, when I clicked on the button to create the bet. Also, the error messages were in a strange format that included the source code. 

The acceptable image formats should be specified at the time of upload. Also, should present an error message at the time of upload, if the incorrect format.

<img width="590" alt="Screen Shot 2022-03-09 at 1 13 50 PM" src="https://user-images.githubusercontent.com/43579946/157515895-a0b1555f-fb0b-42f9-a941-ca877d8ed1c7.png">

<img width="361" alt="Screen Shot 2022-03-09 at 1 13 32 PM" src="https://user-images.githubusercontent.com/43579946/157515886-0e9347b3-d14b-46df-a667-a6207d460760.png">

**Comment by vibhandikyash** [comment]
This issue has been fixed with allowing limited file and changing ipfs endpoint.

**Comment by kalkiboru111** [comment]
Great work
